// Shop config — swap this file per client. Everything customer-facing lives here.
const CATALOG = [
  { sku:"FS1",  en:["Teddy Bear & Roses","White bear with red and peach roses"], es:["Osito y rosas","Osito blanco con rosas rojas"], p:150, e:"🧸" },
  { sku:"FS3",  en:["Te Quiero Red Roses","Red roses with gold script ribbon"], es:["Rosas Te Quiero","Rosas rojas con listón dorado"], p:150, e:"🌹" },
  { sku:"FS2",  en:["Plush Rose Wreath","Pink plush toy in a ring of roses"], es:["Corona con peluche","Peluche rosa entre rosas rojas"], p:150, e:"🎀" },
  { sku:"FS10", en:["White Roses & Lilies","All-white, often chosen for sympathy"], es:["Rosas y lirios blancos","Todo blanco, para condolencias"], p:150, e:"🤍" },
  { sku:"FS4",  en:["Yellow Rose & Hydrangea","Yellow roses with blue hydrangea"], es:["Rosa e hidrangea azul","Rosas amarillas con hidrangea"], p:150, e:"💛" },
  { sku:"FS27", en:["Blush Pink Roses","Soft pink roses and stock"], es:["Rosas rosa pálido","Rosas rosadas suaves y alhelí"], p:150, e:"🌷" },
  { sku:"FS21", en:["Mixed Bouquet & Bear","Gerbera, roses and a soft teddy"], es:["Ramo mixto con osito","Gerberas, rosas y un osito"], p:150, e:"🧸" },
  { sku:"FS5",  en:["Red & White Rose Bear","Two-tone roses with a small teddy"], es:["Osito rosas dos tonos","Rosas rojas y blancas con osito"], p:150, e:"🐻" },
  { sku:"FS18", en:["Daisy, Bear & Balloon","White daisies, teddy bear, balloon"], es:["Margaritas y globo","Margaritas, osito y un globo"], p:130, e:"🎈" },
  { sku:"FS24", en:["Rose Bear Bouquet","Red and cream roses, white bear"], es:["Ramo con osito","Rosas rojas y crema con osito"], p:120, e:"🐻" },
  { sku:"FS6",  en:["Classic Red Roses","Two dozen red roses, hand-wrapped"], es:["Rosas rojas clásicas","Dos docenas envueltas a mano"], p:130, e:"🌹" },
  { sku:"FS32", en:["Red & Pink Roses","Mixed red and blush roses"], es:["Rosas rojas y rosadas","Mezcla de rosas rojas y rosadas"], p:130, e:"🌸" },
  { sku:"FS19", en:["Purple Stock & Gerbera","Purple stock and red gerbera daisies"], es:["Alhelí morado y gerbera","Alhelí morado con gerbera roja"], p:130, e:"💜" },
  { sku:"FS20", en:["Pink Roses, Gold Trim","Pink roses with a gold accent"], es:["Rosas con detalle dorado","Rosas rosadas y toque dorado"], p:130, e:"🌺" },
  { sku:"FS29", en:["Lilies & Red Roses","White lilies and red roses, black vase"], es:["Lirios y rosas rojas","Lirios blancos en florero negro"], p:150, e:"🤍" },
  { sku:"FS11", en:["Tall Decorative Pot","Lilies and roses in a ceramic pot"], es:["Maceta decorativa alta","Lirios y rosas en maceta"], p:200, e:"🪴" },
  { sku:"FS17", en:["Orange Rose & Daisy","Orange roses with white daisies"], es:["Rosa naranja y margarita","Rosas naranjas y margaritas"], p:100, e:"🧡" },
  { sku:"FS26", en:["White Daisy & Red Rose","White daisies with red roses"], es:["Margarita y rosa roja","Margaritas blancas con rosas"], p:100, e:"🌼" },
  { sku:"FS31", en:["Yellow Roses, Gold Vase","Yellow roses with red berries"], es:["Rosas en florero dorado","Rosas amarillas con bayas rojas"], p:80, e:"💛" },
  { sku:"FS30", en:["Sunflower Gold Pot","Sunflower, daisies and red roses"], es:["Girasol maceta dorada","Girasol, margaritas y rosas"], p:80, e:"🌻" },
  { sku:"FS23", en:["Sunflower & Rose","Sunflowers with a single red rose"], es:["Girasol y rosa","Girasoles con una rosa roja"], p:60, e:"🌻" },
  { sku:"FS12", en:["Sunflower Basket","Sunflowers and daisies in a basket"], es:["Canasta de girasoles","Girasoles y margaritas en canasta"], p:60, e:"🧺" },
  { sku:"FS14", en:["Daisy Woven Basket","Daisies and roses in a woven basket"], es:["Canasta tejida","Margaritas y rosas en canasta"], p:60, e:"🌼" },
  { sku:"FS28", en:["Daisy in Golden Vase","White daisies and a yellow rose"], es:["Margaritas en dorado","Margaritas y una rosa amarilla"], p:60, e:"✨" },
  { sku:"FS25", en:["Sunflower & Daisy Pot","Small gold pot, sunflower and daisies"], es:["Girasol en maceta","Maceta dorada con girasol"], p:60, e:"🌻" }
];

const T = {
  en: {
    lang: "English",
    greeting: "Hi! 💐 Thanks for messaging Flor y Sol.\n\nAna and Luis are here to help. What can we do for you today?",
    menu: ["See our arrangements", "Ask a question", "Talk to someone"],
    browseIntro: "Here's what we have right now. Tap any one to see it. 🌷",
    prodHead: "Our arrangements",
    more: "Show more", moreSub: "See the rest of our arrangements", startOver: "← Back to the start",
    order: "Order this one", backList: "← Back to list", backMenu: "← Back",
    talk: "Talk to someone", another: "Another question",
    askMethod: "Beautiful choice. Is this for delivery or pickup?",
    delivery: "Delivery", pickup: "Pickup",
    askAddress: "What's the delivery address?",
    sampleAddress: "450 Oak St, Springfield",
    askWhen: "When do you need it?", today: "Today", tomorrow: "Tomorrow", other: "Another day",
    askCard: "Would you like a card message included?", yes: "Yes", noCard: "No message",
    askCardText: "What should the card say?",
    sampleCard: "Feliz cumpleaños Mamá, te quiero — Ana",
    askName: "Last thing — what name should we put on the order?",
    sampleName: "Ana Reyes",
    summary: (n,pr,pm,d) => "All set, " + n + "! Here's your order:\n\n" + pr.en[0] + " (" + pr.sku + ")\n$" + pr.p + ".00\n" + pm + (d ? " — $" + d : "") + "\n\nTap below to pay securely. Your receipt comes automatically.",
    payBtn: "💳  Pay securely",
    paid: n => "Payment received — thank you, " + n + "! 💐\n\nYour order number is FS-2841.\n\nStripe just emailed your receipt. We'll message you here when it's ready.",
    anythingElse: "Anything else I can help with?", done: "No, thanks", backToMenu: "Back to menu",
    faqHead: "Common questions",
    faqs: [
      ["Hours", "We're open Monday through Saturday, 7:00 AM to 7:00 PM.\n\nClosed Sundays."],
      ["Location", "We're at:\n\n1200 Market St\nSpringfield, CA 90210\n\nStreet parking available."],
      ["Delivery", "We deliver throughout Springfield and the surrounding area.\n\nDelivery cost depends on distance — we'll confirm it with your order."],
      ["Same-day orders", "Often yes! Message us in the morning and we'll do our best.\n\nIt depends on what's in stock that day, so earlier is better."],
      ["Weddings & events", "We design full wedding and event florals — bouquets, ceremony pieces, and centerpieces.\n\nThese are quoted individually. Tap 'Talk to someone' and Ana will go over your date and colors."],
      ["Custom arrangements", "Yes! Tell us your colors or the feeling you're going for and Ana will design something one-of-a-kind."]
    ],
    handoff: "Of course — let me get Luis for you. 🌷\n\nHe'll reply right here shortly. We're open Monday–Saturday, 7 AM to 7 PM.",
    humanReply: "Hi, this is Luis — how can I help you?",
    ph: "Type a message", online: "online", typing: "typing…",
    nStripe: "Customer pays on Stripe's page. Card details never touch WhatsApp, your server, or the shop's Gmail.",
    nEmail: "The shop gets an email now: item, SKU, address, date, card message, phone number, payment confirmed.",
    nPause: "Bot goes quiet. Luis replies from the same business number in the WhatsApp Business app.",
    nResume: "Bot stays paused 2 hours, then picks back up if the customer messages again.",
    nIntro: "Demo — this is what a customer sees in WhatsApp. Tap the blue options."
  },
  es: {
    lang: "Español",
    greeting: "¡Hola! 💐 Gracias por escribir a Flor y Sol.\n\nAna y Luis están para ayudarle. ¿En qué le podemos servir hoy?",
    menu: ["Ver nuestros arreglos", "Hacer una pregunta", "Hablar con alguien"],
    browseIntro: "Esto es lo que tenemos ahora. Toque cualquiera para verlo. 🌷",
    prodHead: "Nuestros arreglos",
    more: "Ver más", moreSub: "Ver el resto de los arreglos", startOver: "← Volver al inicio",
    order: "Ordenar este", backList: "← Regresar a la lista", backMenu: "← Regresar",
    talk: "Hablar con alguien", another: "Otra pregunta",
    askMethod: "Excelente elección. ¿Es para entrega o para recoger?",
    delivery: "Entrega", pickup: "Recoger",
    askAddress: "¿Cuál es la dirección de entrega?",
    sampleAddress: "450 Oak St, Springfield",
    askWhen: "¿Para cuándo lo necesita?", today: "Hoy", tomorrow: "Mañana", other: "Otro día",
    askCard: "¿Desea incluir una tarjeta con mensaje?", yes: "Sí", noCard: "Sin mensaje",
    askCardText: "¿Qué desea que diga la tarjeta?",
    sampleCard: "Feliz cumpleaños Mamá, te quiero — Ana",
    askName: "Por último — ¿a nombre de quién ponemos el pedido?",
    sampleName: "Ana Reyes",
    summary: (n,pr,pm,d) => "¡Todo listo, " + n + "! Su pedido:\n\n" + pr.es[0] + " (" + pr.sku + ")\n$" + pr.p + ".00\n" + pm + (d ? " — $" + d : "") + "\n\nToque abajo para pagar de forma segura. Su recibo llega automáticamente.",
    payBtn: "💳  Pagar de forma segura",
    paid: n => "¡Pago recibido, gracias " + n + "! 💐\n\nSu número de pedido es FS-2841.\n\nStripe le acaba de enviar su recibo. Le avisamos aquí cuando esté listo.",
    anythingElse: "¿Algo más en que le pueda ayudar?", done: "No, gracias", backToMenu: "Volver al menú",
    faqHead: "Preguntas frecuentes",
    faqs: [
      ["Horario", "Abrimos de lunes a sábado, de 7:00 AM a 7:00 PM.\n\nCerrado los domingos."],
      ["Ubicación", "Estamos en:\n\n1200 Market St\nSpringfield, CA 90210\n\nHay estacionamiento en la calle."],
      ["Entregas", "Entregamos en Springfield y los alrededores.\n\nEl costo depende de la distancia — se lo confirmamos con su pedido."],
      ["Pedidos el mismo día", "¡Muchas veces sí! Escríbanos temprano y haremos lo posible.\n\nDepende de lo que tengamos fresco ese día."],
      ["Bodas y eventos", "Diseñamos florales completos para bodas y eventos — ramos, ceremonia y centros de mesa.\n\nCada uno se cotiza personalmente. Toque 'Hablar con alguien' y Ana repasará su fecha y colores."],
      ["Arreglos a medida", "¡Claro! Díganos sus colores o el sentimiento que busca y Ana diseñará algo único."]
    ],
    handoff: "Claro que sí — le comunico con Luis. 🌷\n\nÉl le responde aquí en un momento. Estamos abiertos de lunes a sábado, 7 AM a 7 PM.",
    humanReply: "Hola, le habla Luis — ¿en qué le puedo ayudar?",
    ph: "Escribe un mensaje", online: "en línea", typing: "escribiendo…",
    nStripe: "El cliente paga en la página de Stripe. Los datos de la tarjeta nunca tocan WhatsApp ni el correo de la tienda.",
    nEmail: "La tienda recibe un correo: artículo, SKU, dirección, fecha, mensaje, teléfono, pago confirmado.",
    nPause: "El bot se calla. Luis responde desde el mismo número en la app WhatsApp Business.",
    nResume: "El bot espera 2 horas y luego continúa si el cliente vuelve a escribir.",
    nIntro: "Demostración — esto es lo que ve el cliente en WhatsApp. Toque las opciones azules."
  }
};

module.exports = { CATALOG, T };
